export const electronic_tags = [
'Nintendo',
'Nintendo 64',
'Nintendo Switch',
'GameBoy',
'GameBoy Color',
'Gameboy Advanced',
'Pokémon',
'Nintendo DS',
'GameCube',
'Xbox',
'Xbox 360',
'Xbox One',
'Xbox Series X',
'Playstation',
'Playstation 2',
'Playstation 3',
'Playstation 4',
'Playstation 5',
'Retro',
'Co-Op',
'Multiplayer',
'PVP',
'PVE'
]

export const traditional_tags = [
    'Hasbro',
    'Fantasy',
    'Medieval',
    'WW1',
    'Video Game Theme',
    'Trading Card Game',
    'Modern Warfare',
    'Classic',
    'Civilization',
    'American Civil War',
    'Bluffing',
    'Medical',
    'Rage Inducing',
    'Economy',
    'Party Game',
    'Noire',
    'Mafia',
    'RolePlay',
    'Racing',
    'Travel',
    'Pirates',
    'Military',
    'Book',
    'Farming',
    ]
