"""empty message

Revision ID: 46887ed4a8ed
Revises: ffdc0a98111c
Create Date: 2024-07-09 13:46:48.498278

"""
from alembic import op
import sqlalchemy as sa

import os
environment = os.getenv("FLASK_ENV")
SCHEMA = os.environ.get("SCHEMA")

# revision identifiers, used by Alembic.
revision = '46887ed4a8ed'
down_revision = 'ffdc0a98111c'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('articles',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('title', sa.String(length=50), nullable=False),
    sa.Column('body', sa.String(length=5000), nullable=False),
    sa.Column('ownerId', sa.Integer(), nullable=False),
    sa.Column('articleImage', sa.String(), nullable=False),
    sa.Column('time_created', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=True),
    sa.Column('time_updated', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=True),
    sa.ForeignKeyConstraint(['ownerId'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    if environment == "production":
        op.execute(f"ALTER TABLE articles SET SCHEMA {SCHEMA};")
    op.create_table('products',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=75), nullable=False),
    sa.Column('description', sa.String(length=2000), nullable=False),
    sa.Column('price', sa.Float(), nullable=False),
    sa.Column('isTraditional', sa.Boolean(), nullable=False),
    sa.Column('ownerId', sa.Integer(), nullable=False),
    sa.Column('time_created', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=True),
    sa.Column('time_updated', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=True),
    sa.ForeignKeyConstraint(['ownerId'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    if environment == "production":
        op.execute(f"ALTER TABLE products SET SCHEMA {SCHEMA};")
    op.create_table('articleTags',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('tag', sa.Enum('nintentdo', 'nsixfour', 'switch', 'retro', 'coop', 'multiplayer', 'pvp', 'pve', name='tags'), nullable=False),
    sa.Column('articleId', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['articleId'], ['articles.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    if environment == "production":
        op.execute(f"ALTER TABLE articleTags SET SCHEMA {SCHEMA};")
    op.create_table('productImages',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('image_url', sa.String(), nullable=False),
    sa.Column('productId', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['productId'], ['products.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    if environment == "production":
        op.execute(f"ALTER TABLE productImages SET SCHEMA {SCHEMA};")
    op.create_table('productTags',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('tag', sa.Enum('nintentdo', 'nsixfour', 'switch', 'retro', 'coop', 'multiplayer', 'pvp', 'pve', name='tags'), nullable=False),
    sa.Column('productId', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['productId'], ['products.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    if environment == "production":
        op.execute(f"ALTER TABLE productTags SET SCHEMA {SCHEMA};")
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('producttags')
    op.drop_table('productimages')
    op.drop_table('articleTags')
    op.drop_table('products')
    op.drop_table('articles')
    # ### end Alembic commands ###
