"""Create_Products_and_Articles_tables

Revision ID: 9cda17350893
Revises: ffdc0a98111c
Create Date: 2024-07-09 13:21:27.556590

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '9cda17350893'
down_revision = 'ffdc0a98111c'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('articles',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('title', sa.String(length=50), nullable=False),
    sa.Column('body', sa.String(length=5000), nullable=False),
    sa.Column('ownerId', sa.Integer(), nullable=False),
    sa.Column('articleImage', sa.String(), nullable=False),
    sa.Column('time_created', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=True),
    sa.Column('time_updated', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=True),
    sa.ForeignKeyConstraint(['ownerId'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('products',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=75), nullable=False),
    sa.Column('description', sa.String(length=2000), nullable=False),
    sa.Column('price', sa.Float(), nullable=False),
    sa.Column('isTraditional', sa.Boolean(), nullable=False),
    sa.Column('ownerId', sa.Integer(), nullable=False),
    sa.Column('time_created', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=True),
    sa.Column('time_updated', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=True),
    sa.ForeignKeyConstraint(['ownerId'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('articleTags',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('tag', sa.Enum('nintentdo', 'nsixfour', 'switch', 'retro', 'coop', 'multiplayer', 'pvp', 'pve', name='tags'), nullable=False),
    sa.Column('articleId', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['articleId'], ['articles.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('productImages',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('image_url', sa.String(), nullable=False),
    sa.Column('productId', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['productId'], ['products.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('productTags',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('tag', sa.Enum('nintentdo', 'nsixfour', 'switch', 'retro', 'coop', 'multiplayer', 'pvp', 'pve', name='tags'), nullable=False),
    sa.Column('productId', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['productId'], ['products.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('productTags')
    op.drop_table('productImages')
    op.drop_table('articleTags')
    op.drop_table('products')
    op.drop_table('articles')
    # ### end Alembic commands ###
